### ISSUE TITLE
review working mode against tag charter

### ISSUE THREAD

**Issue by masinter** [w3ctag/w3ctag.github.io#6]
The [TAG charter](http://www.w3.org/2004/10/27-tag-charter.html) lists three elements
- to document and build consensus around principles of Web architecture and to interpret and clarify these principles when necessary;
- to resolve issues involving general Web architecture brought to the TAG;
- to help coordinate cross-technology architecture developments inside and outside W3C.

You have the first one covered.

For the second, it would be helpful some guidance on what issues should be "brought to" the tag and a method to do so without mailing the tag list.

For the third, some guidelines on liaison would also be helpful, or some examples of how the work mode does or doesn't accomplish the mission.  My concern is conflicting overlap with IETF, which, while in TAG charter, doesn't seem to have a clear place in this work mode.

**Comment by torgo** [comment]
Thanks for your input. The TAG has taken this into account in writing our new issue templates and readmes and we feel we have addressed the issues you've raised.
